[alias]
b = "build"
c = "clippy"
d = "doc --no-deps --open"
gen = "generate"
r = "run"

[profile.release]
codegen-units = 1
lto = true

[registries.crates-io]
protocol = "sparse"

[net]
git-fetch-with-cli = true
